db.boards.insert({name: 'life'})
db.boards.insert({name: 'work'})
db.boards.insert({name: 'game'})
db.boards.insert({name: 'etc'})

db.posts.insert({ "title": "生活1", "content": "生活内容1", "board": "life", "userid": "tiexin" })
db.posts.insert({ "title": "生活2", "content": "生活内容2", "board": "life", "userid": "tiexin" })
db.posts.insert({ "title": "生活3", "content": "生活内容3", "board": "life", "userid": "tiexin" })
db.posts.insert({ "title": "生活4", "content": "生活内容4", "board": "life", "userid": "tiexin" })
db.posts.insert({ "title": "生活5", "content": "生活内容5", "board": "life", "userid": "tiexin" })

db.posts.insert({ "title": "工作1", "content": "工作内容1", "board": "life", "userid": "tiexin" })
db.posts.insert({ "title": "工作2", "content": "工作内容2", "board": "life", "userid": "tiexin" })
db.posts.insert({ "title": "工作3", "content": "工作内容3", "board": "life", "userid": "tiexin" })
db.posts.insert({ "title": "工作4", "content": "工作内容4", "board": "life", "userid": "tiexin" })
db.posts.insert({ "title": "工作5", "content": "工作内容5", "board": "life", "userid": "tiexin" })

db.posts.insert({ "title": "游戏1", "content": "游戏内容1", "board": "life", "userid": "tiexin" })
db.posts.insert({ "title": "游戏2", "content": "游戏内容2", "board": "life", "userid": "tiexin" })
db.posts.insert({ "title": "游戏3", "content": "游戏内容3", "board": "life", "userid": "tiexin" })
db.posts.insert({ "title": "游戏4", "content": "游戏内容4", "board": "life", "userid": "tiexin" })
db.posts.insert({ "title": "游戏5", "content": "游戏内容5", "board": "life", "userid": "tiexin" })

db.posts.insert({ "title": "其他1", "content": "其他内容1", "board": "life", "userid": "tiexin" })
db.posts.insert({ "title": "其他2", "content": "其他内容2", "board": "life", "userid": "tiexin" })
db.posts.insert({ "title": "其他3", "content": "其他内容3", "board": "life", "userid": "tiexin" })
db.posts.insert({ "title": "其他4", "content": "其他内容4", "board": "life", "userid": "tiexin" })
db.posts.insert({ "title": "其他5", "content": "其他内容5", "board": "life", "userid": "tiexin" })
