notifications:
  email:
  - guotiexin@gmail.com
  on_success: change  # options: [always|never|change] default: always
  on_failure: always  # options: [always|never|change] default: always
  on_start: never     # options: [always|never|change] default: always
language: node_js
os: osx
node_js:
  - "10"
install:
  - npm install

script:
  - npm run test

cache:
  directories:
    - "./node_modules"
